#!groovy
pipeline {
    agent {
        docker {
            image 'maven:3.6-jdk-11-openj9'
            args '-v $HOME/.m2:/root/.m2:z --network host'
            reuseNode true
        }
    }
    parameters {
        string(name: 'pactConsumerTags', defaultValue: 'CONTRACT-TEST', description: 'Tags to verify')
    }
    environment {
        WORKSPACE="${WORKSPACE}/example/ci/jenkins/cenario_2/pact-provider-sample"
    }
    stages {
        stage ('Run Contract Tests'){
            steps {
                dir("${env.WORKSPACE}") {
                    sh "mvn clean verify " +
                            "-Dpact.provider.version=${GIT_COMMIT} " +
                            "-Dpact.verifier.publishResults=true " +
                            "-Dpact.provider.tag=${params.pactConsumerTags}"
                }
            }
        }
    }
    post {
        success {
            script {
                echo "Contract Generated Successful, now trigger Provider check!"
                build job: "can-i-deploy_Consumer", propagate: true
            }
        }
        failure {
            script {
                echo "\n\nThere are some error on ${env.JOB_NAME} on branch ${env.GIT_BRANCH}" +
                        " You can add some notice if you want, see this page to get an example\n" +
                        "https://www.jenkins.io/doc/pipeline/tour/post/"
            }
        }
    }
}