#!groovy
pipeline {
    agent any
    tools {nodejs "nodeV12"}
    environment {
        WORKSPACE="${WORKSPACE}/example/frontend/old_provider"
        BRANCH_NAME=env.GIT_BRANCH.replace("origin/", "")
    }
    stages {
        stage('Validate Contracts') {
            steps {
                dir("${env.WORKSPACE}") {
                    sh 'npm i --unsafe-perm'
                    sh 'npm run test -- --pact-broker-url=http://pact-broker:9292'
                }
            }
        }
    }
}