#!groovy
pipeline {
  agent any
  environment {
    BRANCH_NAME=env.GIT_BRANCH.replace("origin/", "")
    WORKSPACE="${WORKSPACE}/example/ci/jenkins/pact-consumer-sample"
  }
  stages {
    stage('Build and Publish Pacts') {
      steps {
        dir("${env.WORKSPACE}") {
          sh "chmod +x mvnw"
          sh './mvnw clean verify pact:publish -Dpact.consumer.version=${GIT_COMMIT} -Dpact.tag=CONTRACT-TEST'
        } 
      }
    }
  }

  post {
    success {
      script {
        echo "Contract Generated Successful, now trigger Provider check!"
        build job: "exemplo CI Jenkins - passo 2 - (provider)/${BRANCH_NAME}", propagate: true, wait: true
      }
    }
  }
}