#!groovy
pipeline {
  agent {
    docker {
      image 'maven:3.6-jdk-11-openj9'
      args '-v $HOME/.m2:/root/.m2:z --network host'
      reuseNode true
    }
  }
  environment {
    WORKSPACE="${WORKSPACE}/example/ci/jenkins/cenario_1/pact-consumer-sample"
  }
  stages {
    stage('Build and Publish Pacts') {
      steps {
        dir("${env.WORKSPACE}") {
          sh 'mvn clean verify pact:publish -Dpact.consumer.version=${GIT_COMMIT} -Dpact.tag=CONTRACT-TEST'
        }
      }
    }
  }

  post {
    success {
      script {
        echo "Contract Generated Successful, now trigger Provider check!"
        build job: "cenario_1_passo_2", propagate: true
      }
    }
  }
}