#!groovy
pipeline {
  agent any
  environment {
    WORKSPACE="${WORKSPACE}/example/ci/jenkins/pact-provider-sample"
  }
  parameters {
    string(name: 'pactConsumerTags', defaultValue: 'CONTRACT-TEST', description: 'Tags to verify')
  }
  stages {
    stage ('Run Contract Tests'){
      steps {
        dir("${env.WORKSPACE}") {
          sh "chmod +x mvnw"
          sh "./mvnw clean verify " +
                  "-Dpact.provider.version=${GIT_COMMIT} " +
                  "-Dpact.verifier.publishResults=true " +
                  "-Dpact.provider.tag=${params.pactConsumerTags}"
        } 
      }
    }
  }
  post {
    success {
      script {
        echo "Contract Generated Successful, now trigger Provider check!"
        build job: 'exemplo CI Jenkins - passo 3 - can I deploy ? (consumer)', propagate: true
      }
    }
  }
}